services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: postgres
      POSTGRES_DB: atlasbank
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../InstantTransfers/OutputScript.sql:/docker-entrypoint-initdb.d/sqlscript.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  postgres-data:
